### ISSUE TITLE
Amélioration du nombre de message dans Jeedom Master si Jeedom cible est en cours de redémarrage

### ISSUE THREAD

**Issue by JEALG** [jeedom/plugin-jeelink#53]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire.**
Lors du redémarrage d'un Jeedom Cible, on a un nombre important de message qui apparait dans le centre de message du Jeedom Cible

**Décrivez la solution que vous souhaitez**
Serait-il possible de faire qu'une alerte. car lors des alertes on arrive plus a accéder correctement au Jeedom master

**Décrivez les alternatives que vous avez envisagées**
1 seule alerte si le plugin détecte une absence de connexion 
une autre solution serait d'avoir un message identique pour le centre de message et un message plus détaillé pour les logs

**Contexte supplémentaire
<img width="620" alt="Capture d’écran 2024-07-09 à 19 28 05" src="https://github.com/jeedom/plugin-jeelink/assets/48254791/69897796-540c-48c2-ad58-16933960329a">
<img width="1939" alt="Capture d’écran 2024-07-09 à 19 29 29" src="https://github.com/jeedom/plugin-jeelink/assets/48254791/8b7b2ad5-b956-4403-803d-d81f88b03106">

**Comment by zoic21** [comment]
Bonjour,
Ce plugin n'est plus maintenu au profit de l'utilisation de mqtt manager pour ce genre de lien entre jeedom.
